<html>

<head>


<link href="<?=PATH . 'css/bootstrap.css'; ?>" rel="stylesheet">
<script type="text/javascript" src="<?=PATH . 'js/jquery-1.7.2.min.js?v=1.0';?>"></script>	

<script type="text/javascript" src="<?=PATH . 'js/plugins/qrcode/jquery.qrcode.js';?>"></script>
<script type="text/javascript" src="<?=PATH . 'js/plugins/qrcode/qrcode.js';?>"></script>


<?php $color = explode(',', $this->color); ?>

<style type="text/css" ">

.powered-by{
	text-align: center;
	font-size: 10px;
	color: black;
}

.powered-by a{
	color: black;
	text-decoration: none;
}

ul{
	margin: 0;
	padding: 0;
	list-style: none;
}

.nav li{
	float: left;
	padding: 5px 5px 0px 5px;
}

.nav-info-li{
	border-right: 1px solid <?php echo $this->color; ?>;
	border-bottom: 1px solid <?php echo $this->color; ?>;
	border-left: 1px solid <?php echo $this->color; ?>;
	border-bottom-left-radius: 10px;
}

.nav li a{
	text-decoration: none;
	color: #000000;
}

.nav li a:hover{
	text-decoration: none;
	background-color: inherit;
}

.tab-info, .tab-about, .tab-chipin{
	margin-left: auto;
	margin-right: auto;
	width: 200px;
	height: 135px;
	padding-top: 10px;
}

#qrcode{
	margin: auto;
	width: 100px;
	height: 100px;
}

.about{
	text-align: left;
	overflow: auto;
}

.address{
	text-align: center;
	margin-top: 10px;
	font-size: 8px;
}

.widget-container{
	border-radius: 10px;
	background-color: <?='#'.$color[0];?>;
	background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0%,<?='#'.$color[0];?>),color-stop(100%,<?='#'.$color[1];?>));
	background-image: -webkit-linear-gradient(top,<?='#'.$color[0];?>,<?='#'.$color[1];?>);
	background-image: -moz-linear-gradient(top,<?='#'.$color[0];?>,<?='#'.$color[1];?>);
	background-image: -ms-linear-gradient(top,<?='#'.$color[0];?>,<?='#'.$color[1];?>);
	background-image: -o-linear-gradient(top,<?='#'.$color[0];?>,<?='#'.$color[1];?>);
	background-image: linear-gradient(top,<?='#'.$color[0];?>,<?='#'.$color[1];?>);
	filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=<?='#'.$color[0];?>,endColorstr=<?='#'.$color[1];?>);
}

</style>

<script type="text/javascript" charset="utf-8">
	$(document).ready(function(){
		$(".nav-info-li").css('background-color', '#FFFFFF');
		
		$('#qrcode').qrcode({text: "<?=$this->address;?>", width: 100, height: 100});

		$("#nav-about, #nav-info").click(function(event){
			event.preventDefault();
			
			$this = $(this);
			
			var tab = $this.attr("id").split("-");
			
			$this.parent().siblings().css("background-color", "");
			$this.parent().siblings().css("border", "");
					
			$this.parent().css("background-color", "#FFFFFF");
			
			$(".tab-"+tab[1]).siblings().hide();
			$(".tab-"+tab[1]).show();
		});
		
		$("#widget-preview-button a").click(function(event){
			event.preventDefault();
			$(".nav li").css('background-color', '');
			$("#tab-chipin").show().siblings().hide();
		});
	});
</script>

</head>	

<body style="margin: 0;">
	<div class="widget-container" style="width: <?php echo $this->width; ?>; height: <?php echo $this->height; ?>;">
		
		<div style="height: 20px; font-weight: bold; padding-left: 20px; padding-top: 5px; font-size: 14px; color: #FFFFFF;">
			<?php echo $this->title; ?>
		</div>
		<div style="width: 230px; height: 150px; border-top-left-radius: 10px; border-top-right-radius: 10px; background-color: #FFFFFF; margin-left: auto; margin-right: auto;">
			<div>
				<div class="tab-info">
					<div class="info" style="overflow: auto;">
						<div class="raised" style="float: left; width: 50%; text-align: center;">
							<div>raised</div>
							<h2 style="margin: 0px; font-weight: bold; font-size: 16px; line-height: 25px;">
								<?php echo $this->raised . ' ' . $this->currency; ?>
							</h2>
							<div>
								<?php echo $this->other_raised.' '.$this->other_currency; ?>
							</div>
						</div>
						<div class="goal" style="float: left; width: 50%; text-align: center;">
							<div>goal</div>
							<h2 style="margin: 0px; font-weight: bold; font-size: 16px; line-height: 25px;">
								<?php echo $this->goal . ' ' . $this->currency; ?>
							</h2>
							<div>
								<?php echo $this->other_goal . ' ' . $this->other_currency; ?>
							</div>
						</div>
					</div>
					<div class="progress progress-secondary" style="width: 200px; margin: 5px auto 5px auto; height: 18px; overflow: hidden">
						<div class="bar" style="width: <?php echo $this->progress . '%'; ?>"></div>
					</div>
					<div>
						<div style="margin-left: 120px; font-size: 10px;">Ends <?php echo $this->ending; ?></div>
					</div>
				</div>
				<div class="tab-about" style="display: none;">
					<p class="about">
						<?php echo stripslashes($this->about); ?>
					</p>
				</div>
				<div class="tab-chipin" id="tab-chipin" style="display: none;">
					<div id="qrcode"></div>
					<p class="address">
						<?php echo $this->address;?>
					</p>
				</div>
			</div>
			<div class="tabs" style="overflow: auto;">
				<ul class="nav">
					<li class="nav-info-li"><a class="nav-info" id="nav-info" href="#info">info</a></li>
					<li class="nav-about-li"><a class="nav-about" id="nav-about" href="#about">about</a></li>
				</ul>
			</div>
		</div>
		<div id="widget-preview-button" class="widget-preview-button" style="padding-top: 23px;">
			<?php if(strtotime($this->ending) > strtotime(date("mm/dd/yy")) ):?>
			<a href="#" data-type="info" style="padding: 5px; background-color: orange; border-radius: 15px; cursor: pointer; text-decoration: none; font-weight: bold; color: #FFFFFF; display: block; width: 90px; margin: auto; text-align: center;">Chipin</a>
			<?php endif;?>
		</div>
		<p class="powered-by">Powered by <a target="_blank" href="http://www.bitcoinchipin.com">bitcoinchipin.com</a></p>
	</div>

</body>



</html>