<html>
	
<head>


<link href="<?=PATH . 'css/bootstrap.css';?>" rel="stylesheet">
<script src="<?=PATH . 'js/jquery-1.7.2.min.js?v=1.0';?>"></script>	

<script type="text/javascript" src="<?=PATH . 'js/plugins/qrcode/jquery.qrcode.js';?>"></script>
<script type="text/javascript" src="<?=PATH . 'js/plugins/qrcode/qrcode.js';?>"></script>


<?php $color = explode(',', $this->color); ?>

<style>

.powered-by{
	text-align: center;
	font-size: 6px;
	color: black;
	margin-top: -5px;
}

.powered-by a{
	color: black;
	text-decoration: none;
}

.prog, .info{
	float: left;
	font-size: 10px;
	margin-left: 7px;
}

.prog p, .info p{
	margin: 0;
}

.tab-info, .tab-about, .tab-chipin{
	margin-left: auto;
	margin-right: auto;
	width: 100px;
	height: 40px;
}

.widget-container{
	border-radius: 10px;
	background-color: <?='#'.$color[0];?>;
	background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0%,<?='#'.$color[0];?>),color-stop(100%,<?='#'.$color[1];?>));
	background-image: -webkit-linear-gradient(top,<?='#'.$color[0];?>,<?='#'.$color[1];?>);
	background-image: -moz-linear-gradient(top,<?='#'.$color[0];?>,<?='#'.$color[1];?>);
	background-image: -ms-linear-gradient(top,<?='#'.$color[0];?>,<?='#'.$color[1];?>);
	background-image: -o-linear-gradient(top,<?='#'.$color[0];?>,<?='#'.$color[1];?>);
	background-image: linear-gradient(top,<?='#'.$color[0];?>,<?='#'.$color[1];?>);
	filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=<?='#'.$color[0];?>,endColorstr=<?='#'.$color[1];?>);
}

.chipin-button a, .info-button a{
	width: 50px;
	height: 15px;
	line-height: 15px;	
	font-size: 10px;
	background-color: orange;
	border-radius: 15px;
	cursor: pointer;
	text-decoration: none;
	font-weight: bold;
	color: #FFFFFF;
	display: block;
	margin: 5px auto 0px auto;
	text-align: center;
}

.address{
	font-size: 4px;
	text-align: center;
	margin: 0;
	overflow: hidden;
}

</style>

<script type="text/javascript" charset="utf-8">
	$(document).ready(function(){
		
		$(".chipin-button a").click(function(event){
			event.preventDefault();
			
			$(".tab-info").hide();
			$(".tab-chipin").show();
		});
		
		$(".info-button a").click(function(event){
			event.preventDefault();
			
			$(".tab-chipin").hide();
			$(".tab-info").show();
		});
		
	});
</script>

</head>	

<body style="margin: 0;">

	<div class="widget-container" style="width: <?php echo $this->width; ?>; height: <?php echo $this->height; ?>;">
		<div style="height: 12px; line-height: 12px; font-weight: bold; padding-left: 10px; font-size: 10px; color: white;">
			<?php echo $this->title; ?>
		</div>
		<div style="width: 100px; border-radius: 10px; background-color: #FFFFFF; margin: 0 auto;">
			<div class="tab-info">
				<div style="overflow: auto;">
					<div class="prog"><?php echo $this->progress .'%'; ?></div>
					<div class="info">
						<p>raised <?php echo $this->raised . ' ' . $this->currency; ?></p>
					</div>
					<div class="clear"></div>
				</div>
				<div class="chipin-button">
					<?php if(strtotime($this->ending) > strtotime(date("mm/dd/yy")) ):?>
					<a href="#">Chipin</a>
					<?php endif; ?>
				</div>
			</div>
			<div class="tab-about" style="display: none;">
				<p class="about"><?php echo $this->about; ?></p>
			</div>
			<div class="tab-chipin" id="tab-chipin" style="display: none;">
				<p class="address">
					<?php echo $this->address;?>
				</p>
				<div class="info-button">
					<a href="#">Info</a>
				</div>
			</div>
		</div>
		<p class="powered-by">Powered by <a target="_blank" href="http://www.bitcoinchipin.com">bitcoinchipin.com</a></p>
	</div>

</body>



</html>