<html>
	
<head>


<link href="<?=PATH . 'css/bootstrap.css';?>" rel="stylesheet">
<script src="<?=PATH . 'js/jquery-1.7.2.min.js?v=1.0';?>"></script>	

<script type="text/javascript" src="<?=PATH . 'js/plugins/qrcode/jquery.qrcode.js';?>"></script>
<script type="text/javascript" src="<?=PATH . 'js/plugins/qrcode/qrcode.js';?>"></script>


<?php $color = explode(',', $this->color); ?>

<style type="text/css">
.powered-by{
	text-align: center;
	font-size: 10px;
	color: black;
	display: none;
}

.powered-by a{
	color: black;
	text-decoration: none;
}

#qrcode{
	margin: auto;
	width: 100px;
	height: 100px;
}

.widget-container{
	border-radius: 10px;
	background-color: <?='#'.$color[0];?>;
	background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0%,<?='#'.$color[0];?>),color-stop(100%,<?='#'.$color[1];?>));
	background-image: -webkit-linear-gradient(top,<?='#'.$color[0];?>,<?='#'.$color[1];?>);
	background-image: -moz-linear-gradient(top,<?='#'.$color[0];?>,<?='#'.$color[1];?>);
	background-image: -ms-linear-gradient(top,<?='#'.$color[0];?>,<?='#'.$color[1];?>);
	background-image: -o-linear-gradient(top,<?='#'.$color[0];?>,<?='#'.$color[1];?>);
	background-image: linear-gradient(top,<?='#'.$color[0];?>,<?='#'.$color[1];?>);
	filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=<?='#'.$color[0];?>,endColorstr=<?='#'.$color[1];?>);
}

.progress{
	width: 130px;
}

.chipin a{
	width: 60px;
	height: 18px;
	line-height: 18px;	
	font-size: 10px;
	background-color: orange;
	border-radius: 15px;
	cursor: pointer;
	text-decoration: none;
	font-weight: bold;
	color: #FFFFFF;
	display: block;
	margin: auto;
	text-align: center;
}

.about{
	text-align: left;
	overflow: auto;
}

.raised, .goal{
	float: left;
	margin-left: 5px;
}

.raised p, .goal p{
	font-size: 10px;
}

.info{
	margin-top: -5px;
}

.info p{
	font-size: 8px;
}

.address{
	overflow: hidden;
	text-align: center;
	font-size: 6px;
}

.tabs a{
	font-size: 10px;
}

.progress{
	margin-bottom: 8px !important;
}
</style>

<script type="text/javascript" charset="utf-8">
	$(document).ready(function(){
		$(".nav-info-li").css('background-color', '#FFFFFF');
		
		$('#qrcode').qrcode({text: "<?=$this->address;?>", width: 100, height: 100});

		$("#nav-about, #nav-info").click(function(event){
			event.preventDefault();
			
			$this = $(this);
			
			var tab = $this.attr("id").split("-");
			
			$(".tab-"+tab[1]).siblings().hide();
			$(".tab-"+tab[1]).show();
		});
		
		$("#chipin").click(function(event){
			event.preventDefault();
			
			$(".tab-chipin").show().siblings().hide();
		});
	});
</script>

</head>	

<body style="margin: 0;">

	<div class="widget-container" style="width: <?php echo $this->width; ?>; height: <?php echo $this->height; ?>;">
		
		<div style="height: 16px; line-height: 16px;  font-weight: bold; padding-left: 20px; font-size: 10px; color: #FFFFFF;">  <?php echo $this->title; ?>  </div>
		<div style="width: 220px; height: 40px; border-radius: 10px; background-color: #FFFFFF; margin: 0 auto;">
			<div style="float: left;">
				<div class="tab-info" style="width: 135px; margin: 5px 5px 0px 5px;">
					<div class="progress progress-secondary">
						<div class="bar" style="width: <?php echo $this->progress . '%'; ?>"></div>
					</div>
					<div class="info">
						<p class="raised">Raised <span><?php echo $this->raised . ' ' . $this->currency; ?></span></p>
						<p class="goal">Goal <span><?php echo $this->goal . ' ' . $this->currency; ?></span></p>
					</div>
				</div>
				<div class="tab-about" style="width: 135px; margin: 5px 5px 0px 5px; display: none;">
					<p class="about">
						<?php echo stripslashes($this->about); ?>
					</p>
				</div>
				<div class="tab-chipin" style="width: 135px; margin: 5px 5px 0px 5px; display: none;">
					<p class="address">
						<?php echo $this->address;?>
					</p>
				</div>
			</div>
			<div class="tabs" style="float: left; margin: 5px 5px 0px 5px;">
				<div class="chipin">
					<?php if(strtotime($this->ending) > strtotime(date("mm/dd/yy")) ):?>
					<a href="#" id="chipin">Chipin</a>
					<?php endif; ?>
				</div>
				<div class="tabs">
					<a href="#" class="nav-info" id="nav-info">Info</a>
					<a href="#" class="nav-about" id="nav-about">About</a>
				</div>
			</div>
		</div>
		<p class="powered-by">Powered by <a target="_blank" href="http://www.bitcoinchipin.com">bitcoinchipin.com</a></p>
	</div>

</body>



</html>