
CREATE TABLE users (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email CHARACTER VARYING(500) NOT NULL,
  username CHARACTER VARYING(255) NOT NULL,
  password CHARACTER VARYING(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--ALTER TABLE users ADD UNIQUE INDEX (email);
ALTER TABLE users ADD UNIQUE INDEX (username);

-- XXX: Case-insensitive unique-constraint doesn't seem to work in MySQL. :(
-- ALTER TABLE users ADD UNIQUE INDEX(LOWER(email));


CREATE TABLE widgets (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  owner_id INTEGER UNSIGNED NOT NULL,
  title CHARACTER VARYING(255),
  ending DATETIME,
  currency CHARACTER VARYING(3),
  goal DECIMAL(5,5) UNSIGNED,
  raised DECIMAL(5,5) UNSIGNED DEFAULT 0,
  progress DECIMAL(2,2) UNSIGNED DEFAULT 0,
  width SMALLINT UNSIGNED,
  height SMALLINT UNSIGNED,
  color CHARACTER VARYING(25),
  address CHARACTER VARYING(255),
  about CHARACTER VARYING(255),
  country CHARACTER VARYING(2),
  created DATETIME,
  FOREIGN KEY (owner_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--ALTER TABLE widgets ADD CONSTRAINT widgets_users_fk FOREIGN KEY (owner_id) REFERENCES users (id);
