<script src="<?=PATH;?>js/plugins/datatables/jquery.dataTables.js"></script>
<script src="<?=PATH;?>js/plugins/datatables/DT_bootstrap.js"></script>
<script src="<?=PATH;?>js/plugins/responsive-tables/responsive-tables.js"></script>

<link href="<?=PATH;?>js/plugins/datatables/DT_bootstrap.css" rel="stylesheet">
<link href="<?=PATH;?>js/plugins/responsive-tables/responsive-tables.css" rel="stylesheet">

<link rel="stylesheet" type="text/css" href="<?=PATH;?>js/plugins/lightbox/themes/default/jquery.lightbox.css" />
<!--[if IE 6]>
<link rel="stylesheet" type="text/css" href="<?=PATH;?>js/plugins/lightbox/themes/default/jquery.lightbox.ie6.css" />
<![endif]-->
<script type="text/javascript" src="<?=PATH;?>js/plugins/lightbox/jquery.lightbox.min.js"></script>

<style type="text/css">
	.span6{
		width: 370px;
		min-height: 50px;
	}
	
	.statistics{
		width: 100%;
	}
	
	.statistics td{
		text-align: center;
	}
	
	.statistics-progress{
		color: red;
	}
</style>


<script type="text/javascript">
	
	$(document).ready(function(){
		$('#example').dataTable({
			sDom: "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
			sPaginationType: "bootstrap",
			oLanguage: {
				"sLengthMenu": "_MENU_ records per page"
			}
		});
		
		$(".widget-name").click(function(event){
			event.preventDefault();
			
			$this = $(this);
			
			var html = $(
				"<div class='center'>"+
					"<h3 style='text-align: center;'>Are you sure you want to delete this widget?</h3>"+
					"<h4 style='text-align: center;'>Once ended, you will not be able to restart it.</h5>"+
					"<div style='margin: 40px auto; text-align: center;'>"+
						"<a href='<?=PATH;?>admin/end?id="+$this.attr('id')+"' class='btn btn-danger' style='width: 80px;'>End</a>"+
					"</div>"+
					"<div style='width: "+$this.attr('width')+"px; height: "+$this.attr('height')+"px; margin: 40px auto;'>"+
						"<iframe frameborder='no' framespacing='0' scrolling='no' src='"+$this.attr('href')+"' width='"+$this.attr('width')+"' height='"+$this.attr('height')+"'></iframe>"+
					"</div>"+
				"</div>"
			);
			
			$.lightbox(html, {
				width   : 500,
				height	: 500,
				onOpen: function(){
					$("#cancel").click(function(){
						$(this).remove();
					});
				},
				onClose: function(){
					console.log($(this));
				}
			});
		});
		
	});
	
</script>

<div id="content">
		
	<div class="container">

		<div class="row">
			
			
			<div class="span6">
				<div class="widget widget-table">
	      			<div class="widget-header">
						<h3>
							<i class="icon-bar-chart"></i>
							New Widgets
						</h3>
					</div>
					<div class="widget-content">
						<table class="statistics">
							<tr>
								<td><h1><?php echo $this->new_widgets['today']['count'];?></h1></td>
								<td><h1><?php echo $this->new_widgets['active']['count'];?></h1></td>
								<td><h1><?php echo $this->new_widgets['month']['count'];?></h1></td>
							</tr>
							<tr class="statistics-progress">
								<td style="color: <?php echo ($this->new_widgets['today']['progress'] <= 0) ? 'red' : 'green'; ?>;"><?php echo $this->new_widgets['today']['progress'] . ' %';?></td>
								<td style="color: <?php echo ($this->new_widgets['active']['progress'] <= 0) ? 'red' : 'green'; ?>;"><?php echo $this->new_widgets['active']['progress'] . ' %';?></td>
								<td style="color: <?php echo ($this->new_widgets['month']['progress'] <= 0) ? 'red' : 'green'; ?>;"><?php echo $this->new_widgets['month']['progress'] . ' %';?></td>
							</tr>
							<tr>
								<td>Today</td>
								<td>Active</td>
								<td>Month</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
			<div class="span6">
				<div class="widget widget-table">
	      			<div class="widget-header">
						<h3>
							<i class="icon-bar-chart"></i>
							Ending
						</h3>
					</div>
					<div class="widget-content">
						<table class="statistics">
							<tr>
								<td><h1><?php echo $this->ending_widgets['today']['count'];?></h1></td>
								<td><h1><?php echo $this->ending_widgets['month']['count'];?></h1></td>
							</tr>
							<tr class="statistics-progress">
								<td style="color: <?php echo ($this->ending_widgets['today']['progress'] <= 0) ? 'red' : 'green'; ?>;"><?php echo $this->ending_widgets['today']['progress'] . ' %';?></td>
								<td style="color: <?php echo ($this->ending_widgets['month']['progress'] <= 0) ? 'red' : 'green'; ?>;"><?php echo $this->ending_widgets['month']['progress'] . ' %';?></td>
							</tr>
							<tr>
								<td>Today</td>
								<td>Month</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
			<div class="span6">
      			<div class="widget widget-table">
		  			<div class="widget-header">
						<h3>
							<i class="icon-bar-chart"></i>
							Total Widgets Created
						</h3>
					</div>
					<div class="widget-content">
						<table class="statistics">
							<tr>
								<td><h1><?php echo $this->total_widgets_created['total']['count'];?></h1></td>
							</tr>
							<tr class="statistics-progress">
								<td style="color: <?php echo ($this->total_widgets_created['total']['progress'] <= 0) ? 'red' : 'green'; ?>;"><?php echo $this->total_widgets_created['total']['progress'] . ' %';?></td>
							</tr>
							<tr>
								<td>Total</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
			
		    <div class="span6">
	      		<div class="widget widget-table">
	      			<div class="widget-header">
						<h3>
							<i class="icon-bar-chart"></i>
							Top Countries
						</h3>
					</div>
					<div class="widget-content">
						<table class="table table-bordered table-striped table-highlight">
							<thead>
								<tr>
									<th>Country</th>
									<th>Count</th>
								</tr>
							</thead>
							<tbody>
								<?php foreach($this->top_countries as $country):?>
								<tr>
									<td><?php echo $country['name']?></td>
									<td><?php echo $country['count']?></td>
								</tr>
								<?php endforeach;?>
							</tbody>
						</table>
					</div> <!-- /widget-content -->
				</div> <!-- /widget -->	
		    </div> <!-- /span6 -->
		    
		    <div class="span6">
	      		<div class="widget widget-table">
					<div class="widget-header">
						<h3>
							<i class="icon-bar-chart"></i>
							Fastest Growing
						</h3>
					</div>
					<div class="widget-content">
						<table class="table table-bordered table-striped table-highlight">
							<thead>
								<tr>
									<th>Title</th>
									<th>Progress</th>
								</tr>
							</thead>
							<tbody>
								<?php foreach($this->fastest_growing_widgets as $widget):?>
								<tr>
									<td><?php echo $widget['title'];?></td>
									<td><?php echo $widget['progress'] . ' ' . '%';?></td>
								</tr>
								<?php endforeach;?>
							</tbody>
						</table>
					</div> <!-- /widget-content -->
				</div> <!-- /widget -->	
		    </div> <!-- /span6 -->
			
		    <div class="span6">
	      		<div class="widget widget-table">
					<div class="widget-header">
						<h3>
							<i class="icon-bar-chart"></i>
							Top Active Users
						</h3>
					</div>
					<div class="widget-content">
						<table class="table table-bordered table-striped table-highlight">
							<thead>
								<tr>
									<th>Username</th>
									<th>Count</th>
								</tr>
							</thead>
							<tbody>
								<?php foreach($this->top_active_users as $user):?>
								<tr>
									<td><?php echo $user['username']?></td>
									<td><?php echo $user['count']?></td>
								</tr>
								<?php endforeach;?>
							</tbody>
						</table>
					</div> <!-- /widget-content -->
				</div> <!-- /widget -->	
		    </div> <!-- /span6 -->
			
			
		    <div class="span12">
	      		<div class="widget widget-table">
					<div class="widget-header">				
						<h3>
							<i class="icon-th-list"></i>
							Data Table Plugin							
						</h3>
					</div> <!-- /widget-header -->
					<div class="widget-content">			
						<table class="table table-striped table-bordered table-highlight" id="example">
							<thead>
								<tr>
									<th>Progress</th>
									<th>Title</th>
									<th>Raised</th>
									<th>Goal</th>
									<th>Location</th>
									<th>Status</th>
								</tr>
							</thead>
							<tbody>
								<?php foreach($this->widgets as $widget): ?>
								<tr class="odd gradeX">
									<td>
										<div class="progress progress-secondary progress-striped" style="margin: auto;">
											<div class="bar" style="width: <?php echo $widget['progress'] . '%'; ?>"></div> <!-- /.bar -->
										</div>
									</td>
									<td><a class="widget-name" id="<?=$widget['id'];?>" width="<?=$widget['width'];?>" height="<?=$widget['height'];?>" href="<?php echo PATH . 'client/widget' . $widget["width"] . 'x' . $widget["height"] . '?id=' . $widget["id"] . '&owner_id=' . $widget["owner_id"]; ?>"><?php echo $widget['title'];?></a></td>
									<td><?php echo $widget['raised'] . ' ' . $widget['currency'];?></td>
									<td><?php echo $widget['goal'] . ' ' . $widget['currency'];?></td>
									<td><?php echo $widget['location'];?></td>
									<td></td>
								</tr>
								<?php endforeach; ?>
							</tbody>
						</table>
						
						
					</div> <!-- /widget-content -->
						
				</div> <!-- /widget -->	
				
		    </div> <!-- /span12 -->

		</div> <!-- /row -->
		
		
		
		
	</div> <!-- /.container -->
	
</div> <!-- /#content -->