<script src="<?=PATH;?>js/plugins/datatables/jquery.dataTables.js"></script>
<script src="<?=PATH;?>js/plugins/datatables/DT_bootstrap.js"></script>
<script src="<?=PATH;?>js/plugins/responsive-tables/responsive-tables.js"></script>

<link href="<?=PATH;?>js/plugins/datatables/DT_bootstrap.css" rel="stylesheet">
<link href="<?=PATH;?>js/plugins/responsive-tables/responsive-tables.css" rel="stylesheet"> 

<script type="text/javascript">
	
	$(document).ready(function(){
		$('#example').dataTable({
			sDom: "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
			sPaginationType: "bootstrap",
			oLanguage: {
				"sLengthMenu": "_MENU_ records per page"
			}
		});
	});
	
</script>

<div id="content">
		
	<div class="container">

		<div class="row">
			
		    <div class="span12">
	      		<div class="widget widget-table">
					<div class="widget-header">				
						<h3>
							<i class="icon-th-list"></i>
							Data Table Plugin							
						</h3>
					</div> <!-- /widget-header -->
					<div class="widget-content">			
						<table class="table table-striped table-bordered table-highlight" id="example">
							<thead>
								<tr>
									<th>Progress</th>
									<th>Title</th>
									<th>Raised</th>
									<th>Goal</th>
									<th>Location</th>
									<th>Status</th>
								</tr>
							</thead>
							<tbody>
								<?php foreach($this->widgets as $widget): ?>
								<tr class="odd gradeX">
									<td>
										<div class="progress progress-secondary progress-striped" style="margin: auto;">
											<div class="bar" style="width: <?php echo $widget['progress'] . '%'; ?>"></div> <!-- /.bar -->
										</div>
									</td>
									<td><?php echo $widget['title'];?></td>
									<td><?php echo $widget['raised'] . ' ' . $widget['currency'];?></td>
									<td><?php echo $widget['goal'] . ' ' . $widget['currency'];?></td>
									<td><?php echo $widget['location'];?></td>
									<td></td>
								</tr>
								<?php endforeach; ?>
							</tbody>
						</table>
						
						
					</div> <!-- /widget-content -->
						
				</div> <!-- /widget -->	
				
		    </div> <!-- /span12 -->

		</div> <!-- /row -->
		
		
		
		
	</div> <!-- /.container -->
	
</div> <!-- /#content -->