<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="utf-8">

<title>Bitcoinchipin.com</title>

<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name="apple-mobile-web-app-capable" content="yes"> 


<link href="<?=PATH;?>css/bootstrap.css" rel="stylesheet">
<link href="<?=PATH;?>css/bootstrap-responsive.css" rel="stylesheet">
<link href="<?=PATH;?>css/bootstrap-overrides.css" rel="stylesheet">
<link href="<?=PATH;?>css/ui-lightness/jquery-ui-1.8.21.custom.css" rel="stylesheet">
<link href="<?=PATH;?>css/slate.css" rel="stylesheet">
<link href="<?=PATH;?>css/slate-responsive.css" rel="stylesheet">
<!-- <link href="<?=PATH;?>css/pages/dashboard.css" rel="stylesheet"> -->


<!-- Javascript -->

<script src="<?=PATH;?>js/jquery-1.7.2.min.js?v=1.0"></script>
<script src="<?=PATH;?>js/jquery-ui-1.8.21.custom.min.js?v=1.0"></script>

<script src="<?=PATH;?>js/bootstrap.js?v=1.0"></script>
<script src="<?=PATH;?>js/Slate.js?v=1.0"></script>
<script src="<?=PATH;?>js/plugins/excanvas/excanvas.min.js?v=1.0"></script>

	
</head>

<body>

<div id="nav">
		
	<div class="container">
		
		<a href="javascript:;" class="btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        	<i class="icon-reorder"></i>
      	</a>
		
		<div class="nav-collapse">
			
			<ul class="nav">
				<li class="nav-icon">
					<a href="<?=PATH;?>">
						<i class="icon-home"></i>
						<span>Home</span>
					</a>	    				
				</li>
			</ul>
			
			<ul class="nav pull-right">
		
				<li class="dropdown">					
					<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
						<i class="icon-external-link"></i>
						Statistics
						<b class="caret"></b>
					</a>	
				
					<ul class="dropdown-menu">
						<li><a href="<?=PATH;?>admin/index/">Dashboard</a></li>
						<li><a href="<?=PATH;?>admin/listing/">Listing</a></li>
						<li style="display: none;"><a href="<?=PATH;?>admin/widgets/">Widgets</a></li>
					</ul>    				
				</li>
				<li class="dropdown">					
					<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
						<i class="icon-external-link"></i>
						Account
						<b class="caret"></b>
					</a>	
				
					<ul class="dropdown-menu">
						<li><a href="<?=PATH.'account/changepassword/';?>">Change password</a></li>
						<li><a href="<?=PATH.'signin/signout/';?>">Sign out</a></li>
					</ul>    				
				</li>
			</ul>
		</div> <!-- /.nav-collapse -->
		
	</div> <!-- /.container -->
	
</div> <!-- /#nav -->
	
<?php echo $this->layout()->content;?>

</body>


</html>
