
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" /> 
<title>Bitcoinchipin.com</title>

<link href="<?=PATH;?>css/bootstrap.css" rel="stylesheet" />
<link href="<?=PATH;?>css/bootstrap-responsive.css" rel="stylesheet" />
<link href="<?=PATH;?>css/bootstrap-overrides.css" rel="stylesheet" />

<link href="<?=PATH;?>css/ui-lightness/jquery-ui-1.8.21.custom.css" rel="stylesheet" />
<link href="<?=PATH;?>css/slate.css" rel="stylesheet" />
<link href="<?=PATH;?>css/slate-responsive.css" rel="stylesheet" />
<link href="<?=PATH;?>css/pages/dashboard.css" rel="stylesheet" />

<? /* JavaScript */ ?>
<script src="<?=PATH;?>js/jquery-1.7.2.min.js"></script>
<script src="<?=PATH;?>js/jquery-ui-1.8.21.custom.min.js"></script>
<script src="<?=PATH;?>js/bootstrap.js"></script>
<script src="<?=PATH;?>js/Slate.js"></script>
<script src="<?=PATH;?>js/plugins/excanvas/excanvas.min.js"></script>

<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-39873638-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') +
      '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
