
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" /> 
<title>Bitcoinchipin.com</title>

<link href="<?=PATH;?>css/bootstrap.css" rel="stylesheet" />
<link href="<?=PATH;?>css/bootstrap-responsive.css" rel="stylesheet" />
<link href="<?=PATH;?>css/bootstrap-overrides.css" rel="stylesheet" />

<link href="<?=PATH;?>css/ui-lightness/jquery-ui-1.8.21.custom.css" rel="stylesheet" />
<link href="<?=PATH;?>css/slate.css" rel="stylesheet" />
<link href="<?=PATH;?>css/slate-responsive.css" rel="stylesheet" />
<link href="<?=PATH;?>css/pages/dashboard.css" rel="stylesheet" />

<? /* JavaScript */ ?>
<script src="<?=PATH;?>js/jquery-1.7.2.min.js"></script>
<script src="<?=PATH;?>js/jquery-ui-1.8.21.custom.min.js"></script>
<script src="<?=PATH;?>js/bootstrap.js"></script>
<script src="<?=PATH;?>js/Slate.js"></script>
<script src="<?=PATH;?>js/plugins/excanvas/excanvas.min.js"></script>
