<!DOCTYPE html>
<html lang="en">
  <head>
    <? require_once dirname(__FILE__) . '/head-common.phtml'; ?>

<style type="text/css">

#nav .container, #footer .container{
	width: 1013px;
}

#content .container{
	background: url("<?=PATH;?>img/bkg_top_bar.png") no-repeat scroll 0 0 white;
	box-shadow: 0 1px 5px #AAA;
	width: 979px;
	padding: 17px;
	margin-left: auto;
	margin-right: auto;
}

</style>

	
</head>

<body>

<div id="nav">
	<div class="container">
		<div class="nav-collapse">
			<ul class="nav">
				<li class="nav-icon">
					<a href="<?=PATH;?>">
						<i class="icon-home"></i>
						<span>Home</span>
					</a>	    				
				</li>
			</ul>
			
			
			<ul class="nav pull-right">
				<li class="dropdown">					
					<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
						<i class="icon-external-link"></i>
						Account
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><a href="<?=PATH.'account/changepassword/';?>">Change password</a></li>
						<li><a href="<?=PATH.'signin/signout/';?>">Sign out</a></li>
					</ul>    				
				</li>
			</ul>
			
		</div> <!-- /.nav-collapse -->
		
	</div> <!-- /.container -->
	
</div> <!-- /#nav -->

  <?php echo $this->layout()->content;?>

  <? /*
  <script type="text/javascript"> 
	  (function(){ 
		  var node = document.createElement("script"); 
		  node.setAttribute("type", "text/javascript"); 
		  node.setAttribute("src", "https://app.bugmuncher.com/js/bugMuncher.min.js"); 
		  document.getElementsByTagName("head")[0].appendChild(node); 
	  })(); 

	  var bugmuncher_options = {
		  language:'en',
		  position:'right',
		  show_intro:true,
		  show_preview:true,
		  label_text:'Feedback',
		  api_key:'a67e2158794047ee195c7ff6d523274a2737ab77'
	  };
  </script>
  */ ?>

  </body>
</html>
