<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="utf-8">

<title>Bitcoinchipin.com</title>

<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name="apple-mobile-web-app-capable" content="yes"> 


<link href="<?=PATH;?>css/bootstrap.css" rel="stylesheet">
<link href="<?=PATH;?>css/bootstrap-responsive.css" rel="stylesheet">
<link href="<?=PATH;?>css/bootstrap-overrides.css" rel="stylesheet">

<link href="<?=PATH;?>css/components/signin.css" rel="stylesheet" type="text/css">

<link href="<?=PATH;?>css/ui-lightness/jquery-ui-1.8.21.custom.css" rel="stylesheet">
<link href="<?=PATH;?>css/slate.css" rel="stylesheet">
<link href="<?=PATH;?>css/slate-responsive.css" rel="stylesheet">
<link href="<?=PATH;?>css/pages/dashboard.css" rel="stylesheet">


<!-- Javascript -->

<script src="<?=PATH;?>js/jquery-1.7.2.min.js"></script>
<script src="<?=PATH;?>js/jquery-ui-1.8.21.custom.min.js"></script>
<script src="<?=PATH;?>js/jquery.ui.touch-punch.min.js"></script>
<script src="<?=PATH;?>js/bootstrap.js"></script>

<script src="<?=PATH;?>js/Slate.js"></script>

<script src="<?=PATH;?>js/plugins/excanvas/excanvas.min.js"></script>
<script src="<?=PATH;?>js/plugins/flot/jquery.flot.js"></script>
<script src="<?=PATH;?>js/plugins/flot/jquery.flot.orderBars.js"></script>
<script src="<?=PATH;?>js/plugins/flot/jquery.flot.pie.js"></script>
<script src="<?=PATH;?>js/plugins/flot/jquery.flot.resize.js"></script>
	
</head>

<body>	
	
		<?php echo $this->layout()->content;?>


</body>


</html>