<!DOCTYPE html>
<html lang="en">
  <head>
    <? require_once dirname(__FILE__) . '/head-common.phtml'; ?>

    <? /* TODO: Only include this CSS when on Dashboard! */ ?>
    <link rel="stylesheet" type="text/css" href="/css/components/dashboard.css" />
  </head>
  <body>
    <? $baseDir = dirname(dirname(dirname(dirname(dirname(__FILE__))))); ?>
    <? require "$baseDir/templates/nav-bar.php"; ?>
    <?= $this->layout()->content ?>
    <? require "$baseDir/templates/footer.php"; ?>
  </body>
</html>
