<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="utf-8">

<title>Bitcoinchipin.com</title>

<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name="apple-mobile-web-app-capable" content="yes"> 


<link href="<?=PATH;?>css/bootstrap.css" rel="stylesheet">
<link href="<?=PATH;?>css/bootstrap-responsive.css" rel="stylesheet">
<link href="<?=PATH;?>css/bootstrap-overrides.css" rel="stylesheet">
<link href="<?=PATH;?>css/ui-lightness/jquery-ui-1.8.21.custom.css" rel="stylesheet">
<link href="<?=PATH;?>css/slate.css" rel="stylesheet">
<link href="<?=PATH;?>css/slate-responsive.css" rel="stylesheet">
<link href="<?=PATH;?>css/pages/dashboard.css" rel="stylesheet">


<!-- Javascript -->

<script src="<?=PATH;?>js/jquery-1.7.2.min.js?v=1.0"></script>
<script src="<?=PATH;?>js/jquery-ui-1.8.21.custom.min.js?v=1.0"></script>

<script src="<?=PATH;?>js/bootstrap.js?v=1.0"></script>
<script src="<?=PATH;?>js/Slate.js?v=1.0"></script>
<script src="<?=PATH;?>js/plugins/excanvas/excanvas.min.js?v=1.0"></script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32473688-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<style type="text/css">

#nav .container, #footer .container{
	width: 1013px;
}

#content .container{
	background: url("<?=PATH;?>img/bkg_top_bar.png") no-repeat scroll 0 0 white;
	box-shadow: 0 1px 5px #AAA;
	width: 979px;
	padding: 17px;
	margin-left: auto;
	margin-right: auto;
}

</style>

	
</head>

<body>

<div id="nav">
	<div class="container">
		<div class="nav-collapse">
			<ul class="nav">
				<li class="nav-icon">
					<a href="<?=PATH;?>">
						<i class="icon-home"></i>
						<span>Home</span>
					</a>	    				
				</li>
			</ul>
			
			
			<ul class="nav pull-right">
				<li class="dropdown">					
					<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
						<i class="icon-external-link"></i>
						Account
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><a href="<?=PATH.'account/changepassword/';?>">Change password</a></li>
						<li><a href="<?=PATH.'signin/signout/';?>">Sign out</a></li>
					</ul>    				
				</li>
			</ul>
			
		</div> <!-- /.nav-collapse -->
		
	</div> <!-- /.container -->
	
</div> <!-- /#nav -->
	
<?php echo $this->layout()->content;?>

<script type="text/javascript"> 
	(function(){ 
		var node = document.createElement("script"); 
		node.setAttribute("type", "text/javascript"); 
		node.setAttribute("src", "https://app.bugmuncher.com/js/bugMuncher.min.js"); 
		document.getElementsByTagName("head")[0].appendChild(node); 
	})(); 

	var bugmuncher_options = {
		language:'en',
		position:'right',
		show_intro:true,
		show_preview:true,
		label_text:'Feedback',
		api_key:'a67e2158794047ee195c7ff6d523274a2737ab77'
	};
</script>

</body>


</html>