<!DOCTYPE html>
<html lang="en">
  <head>
    <? require_once dirname(__FILE__) . '/head-common.phtml'; ?>
    <link href="<?=PATH;?>css/components/signin.css" rel="stylesheet" type="text/css" />
    <script src="<?=PATH;?>js/jquery.ui.touch-punch.min.js"></script>
    <script src="<?=PATH;?>js/plugins/flot/jquery.flot.js"></script>
    <script src="<?=PATH;?>js/plugins/flot/jquery.flot.orderBars.js"></script>
    <script src="<?=PATH;?>js/plugins/flot/jquery.flot.pie.js"></script>
    <script src="<?=PATH;?>js/plugins/flot/jquery.flot.resize.js"></script>
  </head>
  <body>
		<?php echo $this->layout()->content; ?>
  </body>
</html>
