<!DOCTYPE html>
<html lang="en">
  <head>
    <? $themeDir = '/measure-theme'; ?>
    <link rel="stylesheet" type="text/css" href="/measure-theme/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="/measure-theme/css/theme.css" />
    <link href='//fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic'
          rel='stylesheet' type='text/css' />

    <? require_once dirname(__FILE__) . '/head-common.phtml'; ?>

    <link href="<?=PATH;?>css/components/signin.css" rel="stylesheet" type="text/css" />
    <script src="<?=PATH;?>js/jquery.ui.touch-punch.min.js"></script>
    <script src="<?=PATH;?>js/plugins/flot/jquery.flot.js"></script>
    <script src="<?=PATH;?>js/plugins/flot/jquery.flot.orderBars.js"></script>
    <script src="<?=PATH;?>js/plugins/flot/jquery.flot.pie.js"></script>
    <script src="<?=PATH;?>js/plugins/flot/jquery.flot.resize.js"></script>
  </head>
  <body>
    <? $baseDir = dirname(dirname(dirname(dirname(dirname(__FILE__))))); ?>
    <? require_once "$baseDir/templates/nav-bar.php"; ?>
		<?php echo $this->layout()->content; ?>
  </body>
</html>
