<link rel="stylesheet" type="text/css" href="<?=PATH;?>js/plugins/lightbox/themes/default/jquery.lightbox.css" />
<!--[if IE 6]>
<link rel="stylesheet" type="text/css" href="<?=PATH;?>js/plugins/lightbox/themes/default/jquery.lightbox.ie6.css" />
<![endif]-->
<script type="text/javascript" src="<?=PATH;?>js/plugins/lightbox/jquery.lightbox.min.js"></script>

<?
  function actionsColumn($widget) { ?>
    <a href="<?= PATH . 'widget-wiz/step-one?w=' . $widget['id'] ?>">Edit</a> |
    <a id="<?= $widget['id']; ?>" width="<?= $widget['width'] ?>" height="<?= $widget['height'] ?>" class="end-widget" href="<?= PATH . 'client/widget' . $widget['width'] . 'x' . $widget['height'] . '?id=' . $widget["id"] . '&owner_id=' . $widget["owner_id"]; ?>">End</a><?
  }

  function widgetsTable($widgets) { ?>
    <table class="table table-bordered table-striped">
      <thead>
        <tr> <th>Progress</th> <th>Name</th> <th>Ending</th>
          <th>Amount</th> <th>Settings</th> </tr>
      </thead>
      <tbody>
        <?php foreach ($widgets as $widget): ?>
          <tr class="even gradeC">
            <td> <div class="progress progress-secondary progress-striped">
              <div class="bar" style="width: <?= $widget['progress'] . '%'; ?>"></div>
            </div> </td>
            <td><?= $widget['title'] ?></td>
            <td>Ends <?= $widget['ending'] ?></td>
            <td>Raised <?= $widget['raised'] . ' ' . $widget['currency'] ?></td>
            <td><?= actionsColumn($widget) ?></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  <? }
?>

<script type="text/javascript">
  $(document).ready(function(){
    $(".end-widget").click(function(event){
      event.preventDefault();

      $this = $(this);

      var html = $(
        "<div class='center'>"+
          "<h3 style='text-align: center;'>Are you sure you want to end this widget?</h3>"+
          "<div style='margin: 40px auto; text-align: center;'>"+
            "<form method='post' action='<?= PATH ?>widget-wiz/end'>" +
              "<input type='hidden' name='id' value='" + $this.attr('id') + "' />" +
              "<button class='btn btn-danger'>End Widget</button>" +
            "</form>" +
            //"<a href='<?=PATH;?>widgets/end?id="+$this.attr('id')+"' class='btn btn-danger' style='width: 80px;'>End</a>"+
          "</div>"+
          "<div style='width: "+$this.attr('width')+"px; height: "+$this.attr('height')+"px; margin: 40px auto;'>"+
            "<iframe frameborder='no' framespacing='0' scrolling='no' src='"+$this.attr('href')+"' width='"+$this.attr('width')+"' height='"+$this.attr('height')+"'></iframe>"+
          "</div>"+
        "</div>"
      );

      $.lightbox(html, {
        width   : 500,
        height	: 500,
        onOpen: function(){
          $("#cancel").click(function(){
            $(this).remove();
          });
        },
        onClose: function(){
          console.log($(this));
        }
      });
    });
  });
</script>

<div id="content">
  <div class="container">

    <div class="widget">

      <div class="widget-header">
        <h3><span class="icon-sitemap"></span>Your Widgets</h3>
        <div class="widget-actions">
          <a href="<?= PATH ?>widget-wiz/create" class="btn btn-small btn-primary">
            <span class="icon-plus"></span>Create new widget</a>
        </div> <!-- /.widget-actions -->
      </div> <!-- /.widget-header -->

      <div class="widget-tabs">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#active">
            <span class="badge badge-success"><?= count($this->activeWidgets) ?></span>
            &nbsp;&nbsp;&nbsp;In Progress</a></li>
          <li><a href="#ended">
            <span class="badge badge-warning"><?= count($this->endedWidgets) ?></span>
            &nbsp;&nbsp;&nbsp;Ended</a></li>
          <li><a href="#all">
            <span class="badge"><?= count($this->allWidgets) ?></span>
            &nbsp;&nbsp;&nbsp;All</a></li>
        </ul>
      </div> <!-- /.widget-tabs -->

      <div class="widget-content">
        <div class="tab-content">
            <div class="tab-pane active" id="active">
              <? if (count($this->activeWidgets) == 0): ?>
                <div class="alert alert-block">
                  <a class="close" data-dismiss="alert" href="#">&times;</a>
                  <h4 class="alert-heading">You do not have any widgets.</h4>
                  Create one now, it's super easy!
                </div>
              <? else: ?>
                <h3>In Progress</h3>
                <br/>
                <?= widgetsTable($this->activeWidgets) ?>
              <? endif; ?>
            </div>
            <div class="tab-pane" id="all">
              <h3>All</h3>
              <br/>
              <?= widgetsTable($this->allWidgets) ?>
            </div>
            <div class="tab-pane" id="ended">
              <h3>Ended</h3>
              <br />
              <?= widgetsTable($this->endedWidgets) ?>
            </div>
          </div>

      </div> <!-- /.widget-content -->

    </div> <!-- /.widget -->

  </div>
</div>

<div id="footer">
  <div class="container">
    &copy; 2012 Propel UI, all rights reserved.
  </div> <!-- /.container -->
</div> <!-- /#footer -->
