<link rel="stylesheet" type="text/css" href="<?=PATH;?>js/plugins/lightbox/themes/default/jquery.lightbox.css" />
<!--[if IE 6]>
<link rel="stylesheet" type="text/css" href="<?=PATH;?>js/plugins/lightbox/themes/default/jquery.lightbox.ie6.css" />
<![endif]-->
<script type="text/javascript" src="<?=PATH;?>js/plugins/lightbox/jquery.lightbox.min.js"></script>
	

<script type="text/javascript">
	$(document).ready(function(){
		$(".end-widget").click(function(event){
			event.preventDefault();
			
			$this = $(this);
			
			var html = $(
				"<div class='center'>"+
					"<h3 style='text-align: center;'>Are you sure you want to delete this widget?</h3>"+
					"<h4 style='text-align: center;'>Once ended, you will not be able to restart it.</h5>"+
					"<div style='margin: 40px auto; text-align: center;'>"+
						"<a href='<?=PATH;?>widgets/end?id="+$this.attr('id')+"' class='btn btn-danger' style='width: 80px;'>End</a>"+
					"</div>"+
					"<div style='width: "+$this.attr('width')+"px; height: "+$this.attr('height')+"px; margin: 40px auto;'>"+
						"<iframe frameborder='no' framespacing='0' scrolling='no' src='"+$this.attr('href')+"' width='"+$this.attr('width')+"' height='"+$this.attr('height')+"'></iframe>"+
					"</div>"+
				"</div>"
			);
			
			$.lightbox(html, {
				width   : 500,
				height	: 500,
				onOpen: function(){
					$("#cancel").click(function(){
						$(this).remove();
					});
				},
				onClose: function(){
					console.log($(this));
				}
			});
		});
	});
</script>

<div id="content">
	<div class="container">	
		<?php if(isset($this->widgets) && empty($this->widgets)):?>
	    <!--/ NOTIFICATION -->
	    <div class="widget">
			<div class="widget-header">
				<h3><i class="icon-sitemap"></i>Your Widgets</h3>
				<div class="widget-actions">
					<a href="<?=PATH;?>widgets/create" class="btn btn-small btn-primary"><i class="icon-plus"></i>Create new widget</a>
				</div> <!-- /.widget-actions -->
			</div> <!-- /.widget-header -->
	
			<div class="widget-tabs">
				<ul class="nav nav-tabs">
				  <li class="active"><a href="#applicants"><span class="badge badge-success">4</span>&nbsp;&nbsp;&nbsp;In Progress</a></li>
				  <li><a href="#rsvps"><span class="badge badge-warning">52</span>&nbsp;&nbsp;&nbsp;Ended</a></li>
				  <li><a href="#registrations"><span class="badge">9</span>&nbsp;&nbsp;&nbsp;All</a></li>
				</ul>
			</div> <!-- /.widget-tabs -->
			
			<div class="widget-content">
				<div class="tab-content">
				    <div class="tab-pane active" id="applicants">
	                    <div class="alert alert-block">
				  <a class="close" data-dismiss="alert" href="#">&times;</a>
				  <h4 class="alert-heading">You do not have any widgets.</h4>
				  Create one now, it's super easy!
				</div>
				    </div>
				    <div class="tab-pane" id="registrations">
				    	<h3>Registrations</h3>
				    </div>
				    <div class="tab-pane" id="rsvps">
				    	<h3>RSVPs</h3>
				    </div>
				  </div>
			</div> <!-- /.widget-content -->
		</div> <!-- /.widget -->
	    <!-- GOOD -->
	    <?php elseif(isset($this->widgets) && !empty($this->widgets)): ?>
		<div class="widget">
			<div class="widget-header">
				<h3>
					<i class="icon-sitemap"></i> 
					Your Widgets
				</h3>
				<div class="widget-actions">
					<a href="<?=PATH;?>widgets/create" class="btn btn-small btn-primary">
						<i class="icon-plus"></i> 
						Create new widget
					</a>
				</div> <!-- /.widget-actions -->
			</div> <!-- /.widget-header -->
			<div class="widget-tabs">
				<ul class="nav nav-tabs">
				  <li class="active"><a href="#applicants"><span class="badge badge-success"><?=$this->in_progress;?></span>&nbsp;&nbsp;&nbsp;In Progress</a></li>
				  <li><a href="#rsvps"><span class="badge badge-warning"><?=$this->ended;?></span>&nbsp;&nbsp;&nbsp;Ended</a></li>
				  <li><a href="#registrations"><span class="badge"><?=$this->all;?></span>&nbsp;&nbsp;&nbsp;All</a></li>
				</ul>
			</div> <!-- /.widget-tabs -->
			<div class="widget-content">
				<div class="tab-content">
				    <div class="tab-pane active" id="applicants">
				    	<h3>In Progress</h3>
				    	<br>
				    	<table class="table table-bordered table-striped">
							<thead>
								<tr>
									<th>Progress</th>
									<th>Name</th>
									<th>Ending</th>
	                                <th>Amount</th>
	                                <th>Settings</th>
								</tr>
							</thead>
							<tbody>
							<?php foreach($this->widgets as $widget): ?>
								<?php if((time()-(60*60*24)) < strtotime($widget['ending'])):?>
								<tr class="even gradeC">
									<td>
										<div class="progress progress-secondary progress-striped">
											<div class="bar" style="width: <?php echo $widget['progress'] . '%'; ?>"></div> <!-- /.bar -->
										</div>
									</td>
									<td><?php echo $widget['title']?></td>
									<td>Ends <?php echo $widget['ending']?></td>
									<td>Raised <?php echo $widget['raised'] . ' ' . $widget['currency']; ?></td>
	                                <td><a href="<?=PATH.'widgets/edit?id='.$widget['id'].'&owner_id='.$widget['owner_id'];?>">Edit</a> | <a id="<?=$widget['id'];?>" width="<?=$widget['width'];?>" height="<?=$widget['height'];?>" class="end-widget" href="<?php echo PATH . 'client/widget' . $widget["width"] . 'x' . $widget["height"] . '?id=' . $widget["id"] . '&owner_id=' . $widget["owner_id"]; ?>">End</a></td>
								</tr>
								<?php endif;?>
							<?php endforeach; ?>
							</tbody>
						</table>
				    </div>
				    <div class="tab-pane" id="registrations">
				    	<h3>All</h3>
				    	<br>
				    	<table class="table table-bordered table-striped">
							<thead>
								<tr>
									<th>Progress</th>
									<th>Name</th>
									<th>Ending</th>
	                                <th>Amount</th>
	                                <th>Settings</th>
								</tr>
							</thead>
							<tbody>
							<?php foreach($this->widgets as $widget): ?>
								<tr class="even gradeC">
									<td>
										<div class="progress progress-secondary progress-striped">
											<div class="bar" style="width: <?php echo $widget['progress'] . '%'; ?>"></div> <!-- /.bar -->
										</div>
									</td>
									<td><?php echo $widget['title']?></td>
									<td>Ends <?=$widget['ending'];?></td>
									<td>Raised <?php echo $widget['raised'] . ' ' . $widget['currency']; ?></td>
	                                <td><a href="<?=PATH.'widgets/edit?id='.$widget['id'].'&owner_id='.$widget['owner_id'];?>">Edit</a> | <a id="<?=$widget['id'];?>" width="<?=$widget['width'];?>" height="<?=$widget['height'];?>" class="end-widget" href="<?php echo PATH . 'client/widget' . $widget["width"] . 'x' . $widget["height"] . '?id=' . $widget["id"] . '&owner_id=' . $widget["owner_id"]; ?>">End</a></td>
								</tr>
							<?php endforeach; ?>
							</tbody>
						</table>
				    </div>
				    <div class="tab-pane" id="rsvps">
				    	<h3>Ended</h3>
				    	<br />
				    	<table class="table table-bordered table-striped">
							<thead>
								<tr>
									<th>Progress</th>
									<th>Name</th>
									<th>Ending</th>
	                                <th>Amount</th>
	                                <th>Settings</th>
								</tr>
							</thead>
							<tbody>
							<?php foreach($this->widgets as $widget): ?>
								<?php if((time()-(60*60*24)) > strtotime($widget['ending'])):?>
								<tr class="even gradeC">
									<td>
										<div class="progress progress-secondary progress-striped">
											<div class="bar" style="width: <?php echo $widget['progress'] . '%'; ?>"></div> <!-- /.bar -->
										</div>
									</td>
									<td><?php echo $widget['title']?></td>
									<td>Ends <?php echo $widget['ending']?></td>
									<td>Raised <?php echo $widget['raised'] . ' ' . $widget['currency']; ?></td>
	                                <td><a href="<?=PATH.'widgets/edit?id='.$widget['id'].'&owner_id='.$widget['owner_id'];?>">Edit</a> | <a id="<?=$widget['id'];?>" width="<?=$widget['width'];?>" height="<?=$widget['height'];?>" class="end-widget" href="<?php echo PATH . 'client/widget' . $widget["width"] . 'x' . $widget["height"] . '?id=' . $widget["id"] . '&owner_id=' . $widget["owner_id"]; ?>">End</a></td>
								</tr>
								<?php endif;?>
							<?php endforeach; ?>
							</tbody>
						</table>
				    </div>
				  </div>
				
			</div> <!-- /.widget-content -->
			
		</div> <!-- /.widget -->
		
		<?php endif;?>
	</div>
</div>

<div id="footer">	
		
	<div class="container">
		
		&copy; 2012 Propel UI, all rights reserved.
		
	</div> <!-- /.container -->		
	
</div> <!-- /#footer -->










