#!/bin/sh

set -e

#echo "Are you sure you want to update production?"
#read line
line="Yes!"
if [ "$line" = "Yes!" ]; then

  BASE_SCRIPT_DIR=`dirname $0`
  cd "$BASE_SCRIPT_DIR/.."
  BASE_CHIPIN_DIR=`pwd`

  TMP_DIR=/tmp/btcchip-up-prod
  rm -Rf "$TMP_DIR"
  mkdir -p "$TMP_DIR"

  SPAREPARTS_SRC_DIR=`realpath ./lib/spare-parts`
  SPAREPARTS_DIR=`dirname "$SPAREPARTS_SRC_DIR"`

  echo "Updating local checkout of My PHP Libs ($SPAREPARTS_DIR)..."
  #bzr up "$SPAREPARTS_DIR"
  echo "Doing export on My PHP Libs source..."
  mkdir "$TMP_DIR/spare-parts"
  #bzr export "$TMP_DIR/my-php-libs" "$SPAREPARTS_DIR"
  cd "$SPAREPARTS_DIR"
  git archive master | tar -x -C "$TMP_DIR/spare-parts"
  echo "Running My PHP Libs test suite..."
  SPAREPARTS_TEST_OUTPUT=`$TMP_DIR/spare-parts/test/test.php`
  SUCCESS_PATTERN="Ran [0-9]+ test functions and [0-9]+ test methods in [0-9]+ classes."
  echo "$SPAREPARTS_TEST_OUTPUT"
  SPAREPARTS_TEST_SUCCESS=`echo "$SPAREPARTS_TEST_OUTPUT" | egrep "$SUCCESS_PATTERN"`
  if [ "$SPAREPARTS_TEST_OUTPUT" != "$SPAREPARTS_TEST_SUCCESS" ]; then
    echo "My PHP Libs test suite failed! Output follows..."
    echo "-------------------------------------------------------------------------------"
    echo "$SPAREPARTS_TEST_OUTPUT"
    exit 1
  fi

  EXPORT_DIR="$TMP_DIR/chipin-src"
  mkdir "$EXPORT_DIR"

  echo "Doing export on Chipin source..."
  cd $BASE_CHIPIN_DIR
  git archive master | tar -x -C "$EXPORT_DIR"

  echo "Copying My PHP Libs to Chipin lib dir..."
  if [ ! -d "$EXPORT_DIR/lib" ]; then
    mkdir "$EXPORT_DIR/lib"
  fi
  cp -a "$TMP_DIR/spare-parts/src" "$EXPORT_DIR/lib/spare-parts"

# TODO: Run test suite!!!

#  echo "Running test script..."
#  cp ./conf/shared-conf.inc.php "$EXPORT_DIR/conf/"
#  TEST_OUTPUT=`$EXPORT_DIR/test/test-all.rb`
#  SUCCESS_LINE=`echo "$TEST_OUTPUT" | grep "all tests passed"`
#  if [ "$SUCCESS_LINE" != "Looks like all tests passed." ]; then
#    echo "Test script failed! Output follows..."
#    echo "-------------------------------------------------------------------------------"
#    echo "$TEST_OUTPUT"
#    exit 1
#  fi

  set -e

  echo "Syncing files with BitcoinChipin.com..."
  rsync --delete -prlv \
    --exclude=public/images/captcha/ --exclude=local-config.ini \
    "$EXPORT_DIR/" chris@bitcoinchipin.com:/home/bitcoin/webapps/bitcoinchipin.com/

  echo "Finished at `date`"

else
  echo "You must type \"Yes!\"."
fi
