<script src="<?=PATH . 'js/plugins/timepicker/jquery.ui.timepicker.min.js?v=1.0';?>"></script>
<link href="<?=PATH . 'js/plugins/timepicker/jquery.ui.timepicker.css?v=1.0';?>" rel="stylesheet">

<link href="<?=PATH . 'css/pages/calendar.css';?>" rel="stylesheet">

<link href="<?=PATH . 'js/plugins/smartwizard/smart_wizard.modified.css?v=1.0';?>" rel="stylesheet"> 	
<script src="<?=PATH . 'js/plugins/smartwizard/jquery.smartWizard-2.0.modified.edit.js?v=1.0';?>"></script>

<link href="<?=PATH . 'js/plugins/msgGrowl/css/msgGrowl.css?v=1.0';?>" rel="stylesheet">
<script src="<?=PATH . 'js/plugins/msgGrowl/js/msgGrowl.js?v=1.0';?>"></script>

<style>
#ui-datepicker-div{
	z-index: 500!important;
}

.msgGrowl-container{
	z-index: 500!important;
}

.stepContainer{
	height: 410px!important;
}

.span8{
	width: 978px;
}
</style>

<script type="text/javascript" charset="utf-8">
	$(document).ready(function(){
		
		$('#wizard').smartWizard({
			transitionEffect:'slideleft',
			enableFinishButton:false
		});	
		
		$('#widget-end-date').datepicker({
			dateFormat: 'mm/dd/yy',
			minDate: +1
		});


		$("#widget-size, #widget-color, #widget-title, #widget-about, #widget-want-to-raise, #widget-end-date, #currency, #widget-bitcoin-address").change(function(){

			var size = $('#widget-size').val();
			var s = size.split('x');
			
			$('#widget-preview, #widget-preview2').attr('src', $('#path').val()+"client/widget"+size+"?preview=true&color="+$('#widget-color').val()+"&address="+$('#widget-bitcoin-address').val()+"&title="+$('#widget-title').val()+"&goal="+$("#widget-want-to-raise").val()+"&about="+$("#widget-about").val()+"&ending="+$('#widget-end-date').val()+"&currency="+$('#currency').val());
			
			$('#widget-preview, #widget-preview2').attr('width', s[0]);
			$('#widget-preview, #widget-preview2').attr('height', s[1]);
		});
		
	});
	
</script>

<input type="hidden" id="path" value="<?php echo PATH; ?>"/>
<input type="hidden" id="widget_id" value="<?=$this->widget->id;?>" />

<div id="content">
	<div class="container">
		<div class="row">
			<div class="span8">
	      		<div class="widget">
					<div class="widget-header">
						<h3><i class="icon-magic"></i>Edit</h3>
					</div> <!-- /widget-header -->
					<div class="widget-content">
						<form id="widgetForm" action="../dashboard/" method="POST" class="form-horizontal">
							<div id="wizard" class="swMain">
								<ul class="wizard-steps">
									<li>
										<a href="#step-1" class="">
											<div class="wizard-step-number">1</div>
											<div class="wizard-step-label">Basic Info</div>
											<div class="wizard-step-bar"></div>
										</a>
									</li>
									<li>
										<a href="#step-2" class="">
											<div class="wizard-step-number">2</div>
											<div class="wizard-step-label">Customize</div>
											<div class="wizard-step-bar"></div>
										</a>
									</li>
									<li>
										<a href="#step-3" class="">
											<div class="wizard-step-number">3</div>
											<div class="wizard-step-label">Finish Widget</div>
											<div class="wizard-step-bar"></div>
										</a>										
									</li>
									
								</ul>
  			
								<div id="step-1">	  				
									<h3>Step 1: Basic Information</h3><br />
									<div class="row-fluid">
										<div class="span6" style="width: 100%;">
											<div class="control-group">
												<label class="control-label" for="widget-title">Title of Widget</label>
												<div class="controls">
													<input type="text" class="input-large" id="widget-title" value="<?=$this->widget->title;?>" maxlength="50">
												</div>
											</div>
											<div class="control-group" id="widget-goal">
												<label class="control-label" for="widget-want-to-raise">I want to raise</label>
												<div class="controls">
													<input type="text" class="input-small" id="widget-want-to-raise" value="<?=$this->widget->goal;?>">
													<span class="help-inline">Please enter a valid number</span>
												</div>
											</div>
											<div class="control-group">
												<label class="control-label" for="widget-end-date">Currency</label>
												<div class="controls">
													<select id="currency" style="width: 100px;">
														<option value="USD" <? if($this->widget->currency == 'USD') echo 'selected="selected"'; ?>>USD</option>
														<option value="EUR" <? if($this->widget->currency == 'EUR') echo 'selected="selected"'; ?>>EUR</option>
														<option value="GBP" <? if($this->widget->currency == 'GBP') echo 'selected="selected"'; ?>>GBP</option>
														<option value="CNY" <? if($this->widget->currency == 'CNY') echo 'selected="selected"'; ?>>CNY</option>
														<option value="CAD" <? if($this->widget->currency == 'CAD') echo 'selected="selected"'; ?>>CAD</option>
														<option value="JPY" <? if($this->widget->currency == 'JPY') echo 'selected="selected"'; ?>>JPY</option>
														<option value="BTC" <? if($this->widget->currency == 'BTC') echo 'selected="selected"'; ?>>BTC</option>
													</select>
												</div>
											</div>                                              
											<div class="control-group">
												<label class="control-label" for="widget-end-date">End Date</label>
												<div class="controls">
													<input type="text" class="input-small" id="widget-end-date"  value="<?=$this->widget->ending;?>">
												</div>
											</div>
											  
											<div class="control-group" id="bitcoin_address_val">
												<label class="control-label" for="widget-bitcoin-address">Bitcoin Address</label>
												<div class="controls">
													<input type="text" class="input-large" id="widget-bitcoin-address" value="<?=$this->widget->address;?>">
													<span class="help-inline">Please provide a valid Bitcoin Address</span>
												</div>
											</div>
										</div> <!-- /span6 -->
									</div> <!-- /row-fluid -->
								</div> <!-- /step -->
					  			<div id="step-2">
					  				<h3>Step 2: Customize Widget</h3>	
					  				<br />
					  				<div class="row-fluid">
					  					<div class="span6">
											<div class="control-group">
												<label class="control-label" for="widget-about">
													About the widget
												</label>
												<div class="controls">
													<textarea class="input-large" id="widget-about" rows="3" maxlength="60"  style="resize: none;height: 60px;width: 260px;"><?=$this->widget->about;?></textarea>
												</div>
											</div>
											<div class="control-group">
												<label class="control-label" for="userlanguage">Size</label>
												<div class="controls">
													<select id="widget-size" name="widget-size">
														<? $s = $this->widget->width.'x'.$this->widget->height; ?>
														<option value="250x250" <? if($s == '250x250') echo 'selected="selected"'; ?>>250 x 250</option>
														<option value="120x60" <? if($s == '120x60') echo 'selected="selected"'; ?>>120 x 60</option>
														<option value="125x125" <? if($s == '125x125') echo 'selected="selected"'; ?>>125 x 125</option>
														<option value="160x250" <? if($s == '160x250') echo 'selected="selected"'; ?>>160 x 250</option>
														<option value="220x220" <? if($s == '220x220') echo 'selected="selected"'; ?>>220 x 220</option>
														<option value="234x60" <? if($s == '234x60') echo 'selected="selected"'; ?>>234 x 60</option>
													</select>
												</div>
											</div>
											<div class="control-group">
												<label class="control-label" for="userlanguage">
													Color
												</label>
												<div class="controls">
													<select id="widget-color" name="widget-color">
														<option value="A9DB80,96C56F" <? if($this->widget->color == 'A9DB80,96C56F') echo 'selected="selected"'; ?>>Green</option>   
														<option value="A67939,845108" <? if($this->widget->color == 'A67939,845108') echo 'selected="selected"'; ?>>Brown</option>
														<option value="3093C7,1C5A85" <? if($this->widget->color == '3093C7,1C5A85') echo 'selected="selected"'; ?>>Blue</option>
														<option value="E0DCDC,707070" <? if($this->widget->color == 'E0DCDC,707070') echo 'selected="selected"'; ?>>Grey</option>
														<option value="F62B2B,D20202" <? if($this->widget->color == 'F62B2B,D20202') echo 'selected="selected"'; ?>>Red</option>
													</select>
												</div>
											</div>
					  					</div> <!-- /span6 -->
					  					<div class="span5 offset1">
					  						<div class="well" style="text-align: center;">
					  							<iframe id="widget-preview" src="<?=PATH.'client/widget'.$this->widget->width.'x'.$this->widget->height.'?id='.$this->widget->id.'&owner_id='.$this->widget->owner_id; ?>" frameborder='no' framespacing='0' scrolling='no' width="<?=$this->widget->width;?>" height="<?=$this->widget->height;?>"></iframe>  								
					  						</div>
					  					</div> <!-- /span6 -->
					  				</div> <!-- /row-fluid -->
					        	</div> <!-- /step -->
					  			<? require dirname(__FILE__) . '/step-3.phtml'; ?>
							</div> <!-- /wizard -->
						</form> 									
					</div> <!-- /widget-content -->
				</div> <!-- /widget -->		    	
		    </div> <!-- /.span12 -->
		</div> <!-- /row -->
	</div> <!-- /.container -->
</div> <!-- /#content -->

<div id="footer">
	<div class="container">&copy; 2012 Propel UI, all rights reserved.</div> <!-- /.container -->		
</div> <!-- /#footer -->
