
<div id="step-3">
	<h3>Step 3: You're done! Just copy and paste the below code into your website.</h3>
	<br />
	<br />
	<div class="row-fluid">
		<div class="span6">
		  <!-- Javascript version -->
		  <div class="control-group">
			  <label class="control-label" for="javascript-version"></label>
			  <div class="controls">
				  <textarea style="height: 110px; width: 400px;" class="input-large"
				            id="javascript-version" rows="3"></textarea>
			  </div>
		  </div>
      <!--
			  Flash version
			  <div class="control-group">
					  <label class="control-label" for="flash-version"></label>
				  <div class="controls">
					  <textarea style="height: 110px;width: 260px;" class="input-large"
					            id="flash-version" rows="3"></textarea>
				  </div>
			  </div>
		  -->
		</div> <!-- /span6 -->
		<div class="span5 offset1">
			<div id="final-widget" class="well" style="text-align: center;">
				<?php /* <iframe id="widget-preview2" src="<?=PATH.'client/widget'.$this->widget->width.'x'.$this->widget->height.'?id='.$this->widget->id.'&owner_id='.$this->widget->owner_id; ?>" frameborder='no' framespacing='0' scrolling='no' width="<?=$this->widget->width;?>" height="<?=$this->widget->height;?>"></iframe> */ ?>
			</div>
		</div> <!-- /span6 -->
	</div> <!-- /row-fluid -->		
</div> <!-- /step -->
