<script type="text/javascript">
	
	function checkTerms() {
		/*
        if (document.getElementById('Field').checked != true) {
            alert('You have to agree to terms and conditions to proceed with your registration.');
            return false;
        }
        */
    	if($("#username").val() == ""){
    		$("#username-error").show();
    		return false;
    	}else{
        	if($("#username-error").size() != 0){
        		$("#username-error").hide();
        	}
        }        

        if($("#password").val() == '' || $("#password").val() != $("#confirm_password").val()){
        	$("#password-error").show();
        	return false;
        }else{
        	if($("#password-error").size() >= 6 && $("#password-error").size() <= 22){
        		$("#password-error").hide();
        	}
        }
		
		return true;
    }

	
</script>


<style type="text/css">
#captcha-input{
	width: 170px;
	float: left;
	margin-left: 30px;
}

.field img{
	float: left;
	height: 40px;
}

body{
	background: white url("<?=PATH;?>img/bkg_body.gif") 50% 0 repeat-x;
}

.page{
	background: url("<?=PATH;?>img/bkg_top_bar.png") no-repeat scroll 0 0 white;
	box-shadow: 0 1px 5px #AAA;
	margin: 20px auto;
	padding: 17px;
	width: 979px;
	min-height: 600px;
}
</style>


<div class="page">
<div class="account-container register">
	<div class="bitcoinchipin-logo">
		<img src="<?=PATH;?>img/logo.jpg" />
	</div>
	<div class="content clearfix">
		<form action="<?=PATH;?>signup/signup/" onsubmit="return checkTerms();" method="post">
			<h1>Create Your Account</h1>			
			<div class="login-social" style="display: none;">
				<p>Sign in using social network:</p>
				<div class="twitter">
					<a href="#" class="btn_1">Login with Twitter</a>				
				</div>
				<div class="fb">
					<a href="#" class="btn_2">Login with Facebook</a>				
				</div>
			</div>
			<div id="password-error" class="alert alert-error" style="display: none;">
				<a class="close" data-dismiss="alert" href="#">×</a>
				<h4 class="alert-heading">Error!</h4>
				Passwords dont match.
			</div>
			<div id="username-error" class="alert alert-error" style="display: none;">
				<a class="close" data-dismiss="alert" href="#">×</a>
				<h4 class="alert-heading">Error!</h4>
				Username cant be empty.
			</div>
			<?php if(isset($this->captcha) && $this->captcha):?>
			<div class="alert alert-error">
				<a class="close" data-dismiss="alert" href="#">×</a>
				<h4 class="alert-heading">Error!</h4>
				Secure code error
			</div>
			<?php endif;?>
			<div class="login-fields">
				<p>Create your free account:</p>
				<div class="field">
					<label for="username">Username:</label>
					<input type="text" id="username" name="username" value="" placeholder="Username:" class="login" />
				</div> <!-- /field -->
				<div class="field">
					<label for="email">Email Address:</label>
					<input type="text" id="email" name="email" value="" placeholder="Email" class="login"/>
				</div> <!-- /field -->
				<div class="field">
					<label for="password">Password:</label>
					<input type="password" id="password" name="password" value="" placeholder="Password" class="login"/>
				</div> <!-- /field -->
				<div class="field">
					<label for="confirm_password">Confirm Password:</label>
					<input type="password" id="confirm_password" name="confirm_password" value="" placeholder="Confirm Password" class="login"/>
				</div> <!-- /field -->
				<?php
					echo $this->form->captcha;
				?>
			</div> <!-- /login-fields -->
			<div class="login-actions">
				<span class="login-checkbox" style="display: none;">
					<input id="Field" name="Field" type="checkbox" class="field login-checkbox" value="First Choice" tabindex="4" />
					<label class="choice" for="Field">I have read and agree with the Terms of Use.</label>
				</span>
				<button class="button btn btn-primary btn-large">Register</button>
			</div> <!-- .actions -->
		</form>
	</div> <!-- /content -->
	
</div> <!-- /account-container -->


<!-- Text Under Box -->
<div class="login-extra">
	Already have an account? <a href="<?=PATH;?>signin/index/">Sign in</a>
</div> <!-- /login-extra -->

</div>