<style type="text/css">

body{
	background: white url("<?=PATH;?>img/bkg_body.gif") 50% 0 repeat-x;
}

.page{
	background: url("<?=PATH;?>img/bkg_top_bar.png") no-repeat scroll 0 0 white;
	box-shadow: 0 1px 5px #AAA;
	margin: 20px auto;
	padding: 17px;
	width: 979px;
	min-height: 600px;
}
</style>

<div class="page">
<div class="account-container login">
	<div class="bitcoinchipin-logo">
		<img src="<?=PATH;?>img/logo.jpg" />
	</div>
	<div class="content clearfix">		
		<form action="" method="post" >
			<div id="login-error" class="alert alert-error">
				<a class="close" data-dismiss="alert" href="#">×</a>
				<h4 class="alert-heading">Error!</h4>
				The link expired.
			</div>
		</form>
		
	</div> <!-- /content -->
	
</div> <!-- /account-container -->


<!-- Text Under Box -->
<div class="login-extra">
	Don't have an account? <a href="<?=PATH;?>signup/index/">Sign Up</a><br/>
	Remind <a href="<?=PATH;?>signin/remind/">Password</a>
</div> <!-- /login-extra -->

</div>
